### ISSUE TITLE
Application Extension Name

### ISSUE THREAD

**Issue by JenNVIDIA** [cadop/ov_dhart#1]
Hey I would recommend changing the extension name because omni is reserved for NVIDIA Application or Extensions.

**Comment by cadop** [comment]
@JenNVIDIA  Thanks for the heads up! Perfect timing, checkout my commit 10 minutes ago :D 

https://github.com/cadop/ov_dhart/commit/5fbd8e05071a715c5d77aa7657cb5a8522c17802
